### ISSUE TITLE
Theming (light/dark themes as well as more) of own components using the SCSS from the MaterialThemeGenerator

### ISSUE THREAD

**Issue by divStar** [arciisine/MaterialThemeGenerator#18]
Hi there!

First off: great website and a great idea - I like it very much!

I have seen https://github.com/arciisine/MaterialThemeGenerator/issues/10, but it didn't explain to me what to do.

I managed to re-use a variable defined in the main stylesheet (`styles.css`) to access e.g. the dark-background color by importing that file.

However: I should not be importing the `styles.scss` file, because apparently things are duplicated (according to https://material.angular.io/guide/theming#defining-a-custom-theme).

How am I supposed to properly import a style generated using your website? Especially if I want at least a light- and dark-theme (seems to be included in the SCSS-content I copied using "Copy Angular scss").
And how am I going to style it if I wanted to include even more themes? (e.g. various primary-/accent-/warn-colors as well as perhaps various styles for my components)

**Comment by divStar** [comment]
After trying it for quite a bit, I must confess that you're a genius!

I am not sure whether my software works in browsers that don't support CSS3 variables. So my questions still stand.

Nevertheless those exported CSS3 variables are awesome, because I can access them in just about any other stylesheet **without** having to `@import` the `styles.(s)css`-file. So I ended up using e.g. `background-color: var(--primary-color);` or the likes - this is awesome!

Still I am curious as to how to solve my problems - I doubt I will ever `@import` the core stylesheet (especially since I know I shouldn't be doing so), but what if I wanted to use the colors e.g. via `map-color($theme-primary)`?

And since the generated stylesheet (from the website) seems to contain light- and darkmode in the same stylesheet, I'd like to know how to use that and especially how to add more...

Again though: thank you very, very much! I hope you are safe and well.

**Comment by arciisine** [comment]
The `scss` file can be imported easily, if the goal is to access the variables.  Additionally, the variable set could be broken out to a shared file that gets imported in the material override.  This would allow you to reference the shared variable set in your own components.

e.g.:
`variables.scss`
```scss
... variable declarations ...
```

`styles.scss`
```scss
@import 'variables.scss';
... 
```

Exporting multiple files from the app is challenging as I'm not building zip files, though that would be a valid PR.  Ultimately the angular team is aiming for CSS variables as a means to style/customize the components, and so that should be the long term goal.  

I believe the only active browser that doesn't support CSS variables is IE11, and the industry as a whole is away from that.  Though the current EOL timeframe is 2025.

**Comment by arciisine** [comment]
Also, the light/dark is defined by the `.theme-alternate` class being attached to the DOM root for the app (most likely body).  Depending on which toggle is selected in the UI, the alternate will be the other theme.

```scss
$theme: mat-light-theme($theme-primary, $theme-accent, $theme-warn);
$altTheme: mat-dark-theme($theme-primary, $theme-accent, $theme-warn);

// Theme Init
@include angular-material-theme($theme);

.theme-alternate {
  @include angular-material-theme($altTheme);
}
```

**Comment by divStar** [comment]
I guess I got it now. Thank you for the explanation and for such a great project!

**Comment by divStar** [comment]
Just in case someone wants to style a class inside a component depending on `.theme-alternate`:
```css
.regular-style {
   color: white;
}
```
```css
.theme-alternate :host .regular-style {
   color: black;
}
```
As you can see you can set up a style while taking into account that the `theme-alternate`-class might have been set. In order to do that, you **must** use the notation in the second example (took me quite a few hours to figure out the right order).

After having done that whenever the class `theme-alternate` is assigned to the `html`-element, your components alternative style (which is described similar to my second example) will be used.

I just hope it saves someone some work!

**Comment by umbe1987** [comment]
> The `scss` file can be imported easily, if the goal is to access the variables. Additionally, the variable set could be broken out to a shared file that gets imported in the material override. This would allow you to reference the shared variable set in your own components.
> 
> e.g.: `variables.scss`
> 
> ```css-scss
> ... variable declarations ...
> ```
> 
> `styles.scss`
> 
> ```css-scss
> @import 'variables.scss';
> ... 
> ```
> 
> Exporting multiple files from the app is challenging as I'm not building zip files, though that would be a valid PR. Ultimately the angular team is aiming for CSS variables as a means to style/customize the components, and so that should be the long term goal.
> 
> I believe the only active browser that doesn't support CSS variables is IE11, and the industry as a whole is away from that. Though the current EOL timeframe is 2025.

It really took me days to understand what to do, but in the end this solved my issue ;)

I had a similar problem as the OP: I needed to change the bg color of a component and I wanted to access the `scss` generated by your (super-neat) project.

At the beginning I simply `@import`ed the file into the theme file of my component, but this risulted in the error

```
WARNING in Exceeded maximum budget for SCSS
```

Here is a step-by-step explanation of what I did (which is basically what you proposed but I write it here explicitly for those like me that are not super experts).

1. **STEP 1**

I created a new file called `src/_variables.scss`, putting there all the variables I needed from the file generated by your project (in my case, I called it `tips-for-families.scss`)
**IMPORTANT**: I did a cut and paste, **NOT** copy and paste, so that the variables are declared only in one file

**_variables.scss**

```
@import '~@angular/material/theming';

$mat-primary: (
  main: #ffcc5f,
  lighter: #fff0cf,
  darker: #ffb943,
  200: #ffcc5f, // For slide toggle,
  contrast : (
    main: $dark-primary-text,
    lighter: $dark-primary-text,
    darker: $dark-primary-text,
  )
);
$theme-primary: mat-palette($mat-primary, main, lighter, darker);

$mat-accent: (
  main: #ffd2cc,
  lighter: #fff2f0,
  darker: #ffc1b9,
  200: #ffd2cc, // For slide toggle,
  contrast : (
    main: $dark-primary-text,
    lighter: $dark-primary-text,
    darker: $dark-primary-text,
  )
);
$theme-accent: mat-palette($mat-accent, main, lighter, darker);

$mat-warn: (
  main: #8ab7dd,
  lighter: #dce9f5,
  darker: #6d9fcf,
  200: #8ab7dd, // For slide toggle,
  contrast : (
    main: $dark-primary-text,
    lighter: $dark-primary-text,
    darker: $dark-primary-text,
  )
);
$theme-warn: mat-palette($mat-warn, main, lighter, darker);

$primary: mat-color($theme-primary);
$accent: mat-color($theme-accent);
$warn: mat-color($theme-warn);
```

2. **STEP 2**

I modified my `angular.json` adding `_variables.scss` to `stylePreprocessorOptions` (taken from https://stackoverflow.com/a/52537105/1979665)

```
...
"styles": [
    "src/tips-for-families.scss",
    "src/styles.css"
  ],
  "stylePreprocessorOptions": {
    "includePaths": [
      "src/styles"
    ]
  },
...
```

3. **STEP 3**

**At the top** of the file generated with your project (again, in my case `tips-for-families.scss`), I `@import`ed the `_variables.scss` (you can now import it as below)

```
@import '~@angular/material/theming';

@import 'variables';
...
```

4. **STEP 4**

:rocket::rocket::rocket::rocket::rocket::rocket:
